-- move_media inserts — generated from reviewed CSV
-- generated by match_move_videos.py --sql

-- 2-on-1-arm-drag — 2-on-1 Arm Drag ← Armdrags & Chops
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000041', 'https://www.youtube.com/watch?v=_h258-ed-no', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- 2-on-1-duck-under — 2-on-1 Duck Under ← 2 on 1 Duck Under
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000038', 'https://www.youtube.com/watch?v=cVjTySx1uZ4', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- 2-on-1-entry — 2-on-1 Entry ← 2 on 1
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000018', 'https://www.youtube.com/watch?v=ytGfsnQmGgM', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- 2-on-1-high-dive — 2-on-1 High Dive ← 2 on 1 Hi Dive
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000039', 'https://www.youtube.com/watch?v=O66IwqnOByE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- 2-on-1-single — 2-on-1 to Single Leg ← Snatch Single
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000040', 'https://www.youtube.com/watch?v=wGwm0qVbu4M', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- ankle-pick — Ankle Pick ← Snap Down to a Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000006', 'https://www.youtube.com/watch?v=0bkIMmQf7TE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- ankle-rides — Ankle Rides ← Ankle Rides
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000093', 'https://www.youtube.com/watch?v=FwA9qL-q8z8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- arm-spin — Arm Spin ← Arm Spin
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000009', 'https://www.youtube.com/watch?v=iiXrSGwfJys', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- arm-throw — Arm Throw ← Arm Spin
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000049', 'https://www.youtube.com/watch?v=iiXrSGwfJys', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- blast-double — Blast Double ← Blast Double
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000004', 'https://www.youtube.com/watch?v=4A2OiHUSbsA', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- bodylock-takedown — Bodylock Takedown ← Finishes Covering Hips
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000045', 'https://www.youtube.com/watch?v=-0MbKdOH12s', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- claw-ride-legs — Claw Ride to Legs ← Referee''s Top Position - Claw Ride to Legs
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000094', 'https://www.youtube.com/watch?v=Zzt9FQMCyNM', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- collar-tie-double — Collar Tie — Level Change Double ← Double Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000020', 'https://www.youtube.com/watch?v=8FyeXO4rviw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- collar-tie-entry — Collar Tie Entry ← Handfighting to Control Tie
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000015', 'https://www.youtube.com/watch?v=4K4mCrXYoKw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- collar-tie-single — Collar Tie — Level Change Single ← Single Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000021', 'https://www.youtube.com/watch?v=0BPnLWYBY1I', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- collar-tie-snap-down — Collar Tie — Snap Down ← Head Snap
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000019', 'https://www.youtube.com/watch?v=-Xi74uWT0vU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- cradle — Cradle ← Cradle
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000100', 'https://www.youtube.com/watch?v=gVFEvCjHcb8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- double-covering-hips — Double Leg — Covering Hips Finish ← Finishes Covering Hips
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000066', 'https://www.youtube.com/watch?v=-0MbKdOH12s', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- double-opponent-turtles — Double Leg — Opponent Turtles ← Double Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000067', 'https://www.youtube.com/watch?v=8FyeXO4rviw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- double-scramble — Double Leg — Scramble ← Double Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000068', 'https://www.youtube.com/watch?v=8FyeXO4rviw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- double-to-hic — Double to Hi-C Conversion ← High Crotch Change Off to Double
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000069', 'https://www.youtube.com/watch?v=ehtf3Y5g6BI', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- double-to-single — Double to Outside Single ← Double Leg Outside Step
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000070', 'https://www.youtube.com/watch?v=OcOK0qaEF98', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- double-under-duck-under — Double Underhook — Duck Under ← 2 on 1 Duck Under
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000036', 'https://www.youtube.com/watch?v=cVjTySx1uZ4', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- double-under-firemans — Double Underhook — Fireman's Carry ← Fireman''s Carry Inline Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000037', 'https://www.youtube.com/watch?v=BReKpgsEOaM', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- double-under-hic — Double Underhook — Hi-C ← Inside Step Penetration   Hi C
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000034', 'https://www.youtube.com/watch?v=b1DwJIJgCIQ', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- duck-under — Duck Under ← 2 on 1 Duck Under
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000010', 'https://www.youtube.com/watch?v=cVjTySx1uZ4', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- firemans-inline — Fireman's Carry — Inline Finish ← Fireman''s Carry Inline Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000065', 'https://www.youtube.com/watch?v=BReKpgsEOaM', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- firemans-kelly — Fireman's Carry — Kelly Finish ← Fireman''s Carry Kelly Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000064', 'https://www.youtube.com/watch?v=-X-AyCR4zC0', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- front-headlock-ankle-pick — Front Headlock — Ankle Pick ← Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000056', 'https://www.youtube.com/watch?v=x-PIwrkcuIo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- front-headlock-chop — Front Headlock — Chop / Finish ← Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000051', 'https://www.youtube.com/watch?v=x-PIwrkcuIo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- front-headlock-go-behind — Front Headlock — Go Behind ← Front Headlock Go Behind
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000052', 'https://www.youtube.com/watch?v=jIUdo33o3ew', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- front-headlock-reset — Front Headlock — Reset to Neutral ← Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000054', 'https://www.youtube.com/watch?v=x-PIwrkcuIo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- front-headlock-shuck-by — Front Headlock — Shuck By ← Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000053', 'https://www.youtube.com/watch?v=x-PIwrkcuIo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- front-headlock-snap-spin — Front Headlock — Snap and Spin ← Snap & Spin
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000055', 'https://www.youtube.com/watch?v=fUARd8ssOVE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- front-headlock-throw — Front Headlock — Throw ← Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000057', 'https://www.youtube.com/watch?v=x-PIwrkcuIo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- gut-wrench-turtle — Gut Wrench from Turtle ← Gut Wrench
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000105', 'https://www.youtube.com/watch?v=f1fJcbiSlcY', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- half-nelson — Half Nelson ← Half Nelson
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000089', 'https://www.youtube.com/watch?v=5DFJOOs-eVQ', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- head-and-arm — Head & Arm ← Head & Arm
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000101', 'https://www.youtube.com/watch?v=3sXklJiRqq8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- head-outside-single — Head Outside Single ← Snatch Single
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000008', 'https://www.youtube.com/watch?v=wGwm0qVbu4M', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- head-snap — Head Snap ← Head Snap
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000012', 'https://www.youtube.com/watch?v=-Xi74uWT0vU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- hic-outside-finish — Hi-C — Outside Finish ← High Crotch Outside Step Penetration
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000062', 'https://www.youtube.com/watch?v=XgvA-g8CFVk', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- hic-pop-finish — Hi-C — Pop Finish ← High Crotch   Pop Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000059', 'https://www.youtube.com/watch?v=GwRZj65x2xE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- hic-stuff-head — Hi-C Counter — Stuff Head ← High Crotch Counter   Stuff Head
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000063', 'https://www.youtube.com/watch?v=RWqifP1lYSw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- hic-to-double — Hi-C — Convert to Double ← High Crotch Change Off to Double
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000060', 'https://www.youtube.com/watch?v=ehtf3Y5g6BI', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- hic-to-single — Hi-C — Convert to Single ← Single Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000061', 'https://www.youtube.com/watch?v=0BPnLWYBY1I', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- hip-dump — Hip Dump ← Hip Dump
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000050', 'https://www.youtube.com/watch?v=i0fP5Q8c1kc', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- inside-tie-double — Inside Tie — Level Change Double ← Double Leg Inside Step
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000024', 'https://www.youtube.com/watch?v=SfmLZMiUEUM', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- inside-tie-entry — Inside Tie Entry ← Inside Tie & Elbow Tie
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000016', 'https://www.youtube.com/watch?v=iAgE1NmnGU0', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- inside-tie-hic — Inside Tie — Level Change Hi-C ← High Crotch Inside Step Penetration
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000025', 'https://www.youtube.com/watch?v=witUsu1OzX8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- inside-tie-snap-down — Inside Tie — Snap Down ← Head Snap
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000023', 'https://www.youtube.com/watch?v=-Xi74uWT0vU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- inside-tie-to-underhook — Inside Tie to Underhook ← Neutral Position - Underhooks Head Position
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000026', 'https://www.youtube.com/watch?v=j3869U-uCCo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- level-change-double — Level Change — Double Leg ← Double Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000001', 'https://www.youtube.com/watch?v=8FyeXO4rviw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- level-change-hic — Level Change — Hi-C ← High Crotch Inside Step Penetration
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000002', 'https://www.youtube.com/watch?v=witUsu1OzX8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- level-change-single — Level Change — Single Leg ← Single Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000003', 'https://www.youtube.com/watch?v=0BPnLWYBY1I', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- low-single — Low Single ← Snatch Single
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000007', 'https://www.youtube.com/watch?v=wGwm0qVbu4M', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- pop-and-chop — Pop & Chop ← Pop & Chop
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000096', 'https://www.youtube.com/watch?v=49bYMsfR6xg', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- pop-and-go — Pop & Go ← Pop & Go
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000095', 'https://www.youtube.com/watch?v=drBu9cpKH3Q', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- pop-chop-bar-arms — Pop & Chop to Bar Arms ← Pop & Chop to Bar Arms
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000097', 'https://www.youtube.com/watch?v=xah_aUIsuQg', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- pop-chop-cheap-tilt — Pop & Chop to Near Wrist Cheap Tilt ← Pop & Chop to a Near Wrist Cheap Tilt
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000098', 'https://www.youtube.com/watch?v=jelOYSlTKtI', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- pop-chop-far-side-tilt — Pop & Chop to Far Side Tilt ← Pop & Chop to a Far Side Tilt
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000099', 'https://www.youtube.com/watch?v=kkhxdmy8nic', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- pummeling-arm-drag — Pummeling to Arm Drag ← Armdrags & Chops
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000033', 'https://www.youtube.com/watch?v=_h258-ed-no', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- reverse-headlock — Reverse Headlock ← Headlock Defense Part II
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000048', 'https://www.youtube.com/watch?v=gLEabYdy_Tk', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- sag-headlock — Sag Headlock ← Headlock Defense Part I   Throw Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000047', 'https://www.youtube.com/watch?v=iAT0HViIXK8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- short-sit — Short Sit ← Short Sit
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000083', 'https://www.youtube.com/watch?v=78CgLjI3Vgg', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- short-sit-head-post — Short Sit to Head Post ← Short Sit to a Head Post
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000086', 'https://www.youtube.com/watch?v=s4Stwx0hP8s', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- short-sit-stand-up — Short Sit to Stand Up ← Short Sit to a Stand Up
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000085', 'https://www.youtube.com/watch?v=hDrypwAVVaE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- short-sit-switch — Short Sit to Switch ← Short Sit to a Switch
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000084', 'https://www.youtube.com/watch?v=xKvMJ4PWSTI', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- single-ankle-turn — Single Leg — Ankle Turn Finish ← Sweep Single   Head Inside
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000073', 'https://www.youtube.com/watch?v=1XeFyfGLsY0', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- single-back-door — Single Leg — Back Door ← Single Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000078', 'https://www.youtube.com/watch?v=0BPnLWYBY1I', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- single-chest-to-back — Single Leg — Chest to Back Finish ← Sweep Single   Head Outside
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000072', 'https://www.youtube.com/watch?v=tOyeuv1xCSs', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- single-outside-finish — Single Leg — Outside Finish ← Sweep Single   Head Outside
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000071', 'https://www.youtube.com/watch?v=tOyeuv1xCSs', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- single-run-the-pipe — Single Leg — Run the Pipe ← Sweep Single   Run the Pipe Finish Head Inside
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000077', 'https://www.youtube.com/watch?v=0732LbzcXGc', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- single-stuff-head — Single Leg Counter — Stuff Head ← Single Leg Counter   Stuff Head
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000080', 'https://www.youtube.com/watch?v=VRussZAawxs', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- single-sweep-head-inside — Single Leg — Sweep Head Inside ← Sweep Single   Head Inside
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000074', 'https://www.youtube.com/watch?v=1XeFyfGLsY0', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- single-sweep-head-outside — Single Leg — Sweep Head Outside ← Sweep Single   Head Outside
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000075', 'https://www.youtube.com/watch?v=tOyeuv1xCSs', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- single-tree-top — Single Leg — Tree Top Finish ← Sweep Single   Tree Top Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000076', 'https://www.youtube.com/watch?v=pG5WynBZRhU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- snap-down — Snap Down ← Head Snap
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000011', 'https://www.youtube.com/watch?v=-Xi74uWT0vU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- snatch-single — Snatch Single ← Snatch Single
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000005', 'https://www.youtube.com/watch?v=wGwm0qVbu4M', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- spiral-ride — Spiral Ride ← Spiral Ride
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000090', 'https://www.youtube.com/watch?v=W7SvQct6NIY', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- spiral-ride-arm-turk — Spiral Ride to Arm Turk ← Spiral Ride to Arm Turk
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000092', 'https://www.youtube.com/watch?v=mqngp-Mt_IY', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- spiral-ride-leg-turk — Spiral Ride to Leg Turk ← Spiral Ride to Leg Turk
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000091', 'https://www.youtube.com/watch?v=dS5RQK43Ino', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- sprawl-defense — Sprawl Defense ← Downblock & Sprawl
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000014', 'https://www.youtube.com/watch?v=YKH3oShF3Fc', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- sprawl-to-front-headlock — Sprawl to Front Headlock ← Snap Down to a Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000013', 'https://www.youtube.com/watch?v=0bkIMmQf7TE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- stand-up — Stand Up ← Stand Up
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000081', 'https://www.youtube.com/watch?v=VwytIfWS1Ws', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- stand-up-turtle — Stand Up from Turtle ← Stand Up
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000103', 'https://www.youtube.com/watch?v=VwytIfWS1Ws', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- switch — Switch ← Switch
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000082', 'https://www.youtube.com/watch?v=koErfJdRCfA', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- turk-lock — Turk Lock ← Turks
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000102', 'https://www.youtube.com/watch?v=i9gzCppt79Y', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- underhook-duck-under — Underhook — Duck Under ← 2 on 1 Duck Under
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000029', 'https://www.youtube.com/watch?v=cVjTySx1uZ4', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- underhook-entry — Underhook Entry ← Neutral Position - Underhooks Head Position
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000017', 'https://www.youtube.com/watch?v=j3869U-uCCo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- underhook-hic — Underhook — Hi-C ← High Crotch Inside Step Penetration
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000027', 'https://www.youtube.com/watch?v=witUsu1OzX8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- whizzer-trick-knee — Whizzer — Trick Knee ← Neutral Position Offense - Trick Knee Whizzer
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000042', 'https://www.youtube.com/watch?v=7Sy_Akka8RU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-2-on-1-arm-drag — 2-on-1 Arm Drag ← Armdrags & Chops
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000154', 'https://www.youtube.com/watch?v=_h258-ed-no', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-2-on-1-duck-under — 2-on-1 Duck Under ← 2 on 1 Duck Under
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000151', 'https://www.youtube.com/watch?v=cVjTySx1uZ4', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-2-on-1-entry — 2-on-1 Entry ← 2 on 1
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000131', 'https://www.youtube.com/watch?v=ytGfsnQmGgM', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-2-on-1-high-dive — 2-on-1 High Dive ← 2 on 1 Hi Dive
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000152', 'https://www.youtube.com/watch?v=O66IwqnOByE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-2-on-1-single — 2-on-1 to Single Leg ← Snatch Single
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000153', 'https://www.youtube.com/watch?v=wGwm0qVbu4M', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-ankle-lace — Ankle Lace ← Ankle Lace
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000191', 'https://www.youtube.com/watch?v=g9nMnsCRPgg', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-ankle-lace-defense — Ankle Lace Defense — Catch the Ankle ← Ankle Lace Defense
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000192', 'https://www.youtube.com/watch?v=lBWYC3NLm64', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-ankle-pick — Ankle Pick ← Snap Down to a Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000119', 'https://www.youtube.com/watch?v=0bkIMmQf7TE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-arm-spin — Arm Spin ← Arm Spin
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000122', 'https://www.youtube.com/watch?v=iiXrSGwfJys', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-arm-throw — Arm Throw ← Arm Spin
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000161', 'https://www.youtube.com/watch?v=iiXrSGwfJys', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-blast-double — Blast Double ← Blast Double
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000117', 'https://www.youtube.com/watch?v=4A2OiHUSbsA', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-bodylock-takedown — Bodylock Takedown ← Finishes Covering Hips
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000157', 'https://www.youtube.com/watch?v=-0MbKdOH12s', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-collar-tie-double — Collar Tie — Level Change Double ← Double Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000133', 'https://www.youtube.com/watch?v=8FyeXO4rviw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-collar-tie-entry — Collar Tie Entry ← Handfighting to Control Tie
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000128', 'https://www.youtube.com/watch?v=4K4mCrXYoKw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-collar-tie-single — Collar Tie — Level Change Single ← Single Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000134', 'https://www.youtube.com/watch?v=0BPnLWYBY1I', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-collar-tie-snap-down — Collar Tie — Snap Down ← Head Snap
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000132', 'https://www.youtube.com/watch?v=-Xi74uWT0vU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-double-covering-hips — Double Leg — Covering Hips Finish ← Finishes Covering Hips
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000179', 'https://www.youtube.com/watch?v=-0MbKdOH12s', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-double-opponent-turtles — Double Leg — Opponent Turtles ← Double Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000180', 'https://www.youtube.com/watch?v=8FyeXO4rviw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-double-scramble — Double Leg — Scramble ← Double Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000181', 'https://www.youtube.com/watch?v=8FyeXO4rviw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-double-to-hic — Double to Hi-C Conversion ← High Crotch Change Off to Double
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000182', 'https://www.youtube.com/watch?v=ehtf3Y5g6BI', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-double-to-single — Double to Outside Single ← Double Leg Outside Step
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000183', 'https://www.youtube.com/watch?v=OcOK0qaEF98', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-double-under-duck-under — Double Underhook — Duck Under ← 2 on 1 Duck Under
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000149', 'https://www.youtube.com/watch?v=cVjTySx1uZ4', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-double-under-firemans — Double Underhook — Fireman's Carry ← Fireman''s Carry Inline Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000150', 'https://www.youtube.com/watch?v=BReKpgsEOaM', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-double-under-hic — Double Underhook — Hi-C ← Inside Step Penetration   Hi C
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000147', 'https://www.youtube.com/watch?v=b1DwJIJgCIQ', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-duck-under — Duck Under ← 2 on 1 Duck Under
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000123', 'https://www.youtube.com/watch?v=cVjTySx1uZ4', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-firemans-inline — Fireman's Carry — Inline Finish ← Fireman''s Carry Inline Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000178', 'https://www.youtube.com/watch?v=BReKpgsEOaM', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-firemans-kelly — Fireman's Carry — Kelly Finish ← Fireman''s Carry Kelly Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000177', 'https://www.youtube.com/watch?v=-X-AyCR4zC0', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-front-headlock-ankle-pick — Front Headlock — Ankle Pick ← Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000169', 'https://www.youtube.com/watch?v=x-PIwrkcuIo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-front-headlock-chop — Front Headlock — Chop / Finish ← Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000164', 'https://www.youtube.com/watch?v=x-PIwrkcuIo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-front-headlock-go-behind — Front Headlock — Go Behind ← Front Headlock Go Behind
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000165', 'https://www.youtube.com/watch?v=jIUdo33o3ew', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-front-headlock-reset — Front Headlock — Reset to Neutral ← Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000167', 'https://www.youtube.com/watch?v=x-PIwrkcuIo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-front-headlock-shuck-by — Front Headlock — Shuck By ← Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000166', 'https://www.youtube.com/watch?v=x-PIwrkcuIo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-front-headlock-snap-spin — Front Headlock — Snap and Spin ← Snap & Spin
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000168', 'https://www.youtube.com/watch?v=fUARd8ssOVE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-front-headlock-throw — Front Headlock — Throw ← Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000170', 'https://www.youtube.com/watch?v=x-PIwrkcuIo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-gut-wrench — Gut Wrench ← Gut Wrench
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000189', 'https://www.youtube.com/watch?v=f1fJcbiSlcY', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-gut-wrench-defense — Gut Wrench Defense — Hips Square ← Gut Wrench Defense   Hips and Shoulders Square and Heavy
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000190', 'https://www.youtube.com/watch?v=_ZVeAIMLWr8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-gut-wrench-turtle — Gut Wrench from Turtle ← Gut Wrench
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000201', 'https://www.youtube.com/watch?v=f1fJcbiSlcY', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-head-outside-single — Head Outside Single ← Snatch Single
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000121', 'https://www.youtube.com/watch?v=wGwm0qVbu4M', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-head-snap — Head Snap ← Head Snap
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000125', 'https://www.youtube.com/watch?v=-Xi74uWT0vU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-hic-outside-finish — Hi-C — Outside Finish ← High Crotch Outside Step Penetration
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000175', 'https://www.youtube.com/watch?v=XgvA-g8CFVk', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-hic-pop-finish — Hi-C — Pop Finish ← High Crotch   Pop Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000172', 'https://www.youtube.com/watch?v=GwRZj65x2xE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-hic-stuff-head — Hi-C Counter — Stuff Head ← High Crotch Counter   Stuff Head
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000176', 'https://www.youtube.com/watch?v=RWqifP1lYSw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-hic-to-double — Hi-C — Convert to Double ← High Crotch Change Off to Double
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000173', 'https://www.youtube.com/watch?v=ehtf3Y5g6BI', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-hic-to-single — Hi-C — Convert to Single ← Single Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000174', 'https://www.youtube.com/watch?v=0BPnLWYBY1I', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-hip-dump — Hip Dump ← Hip Dump
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000163', 'https://www.youtube.com/watch?v=i0fP5Q8c1kc', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-inside-tie-double — Inside Tie — Level Change Double ← Double Leg Inside Step
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000137', 'https://www.youtube.com/watch?v=SfmLZMiUEUM', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-inside-tie-entry — Inside Tie Entry ← Inside Tie & Elbow Tie
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000129', 'https://www.youtube.com/watch?v=iAgE1NmnGU0', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-inside-tie-hic — Inside Tie — Level Change Hi-C ← High Crotch Inside Step Penetration
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000138', 'https://www.youtube.com/watch?v=witUsu1OzX8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-inside-tie-snap-down — Inside Tie — Snap Down ← Head Snap
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000136', 'https://www.youtube.com/watch?v=-Xi74uWT0vU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-inside-tie-to-underhook — Inside Tie to Underhook ← Neutral Position - Underhooks Head Position
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000139', 'https://www.youtube.com/watch?v=j3869U-uCCo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-leg-lace-cartwheel — Leg Lace — Cartwheel Finish ← Par Terre Offense   Leg Lace with Cartwheel Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000195', 'https://www.youtube.com/watch?v=HWdkrx8LsQE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-level-change-double — Level Change — Double Leg ← Double Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000114', 'https://www.youtube.com/watch?v=8FyeXO4rviw', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-level-change-hic — Level Change — Hi-C ← High Crotch Inside Step Penetration
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000115', 'https://www.youtube.com/watch?v=witUsu1OzX8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-level-change-single — Level Change — Single Leg ← Single Leg
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000116', 'https://www.youtube.com/watch?v=0BPnLWYBY1I', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-low-lock-gut-wrench — Low Lock Gut Wrench ← Par Terre Offense   Low Lock Gut Wrench
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000194', 'https://www.youtube.com/watch?v=WJ2GP8EYVjU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-low-single — Low Single ← Snatch Single
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000120', 'https://www.youtube.com/watch?v=wGwm0qVbu4M', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-par-terre-fighting-lock — Par Terre — Fighting the Lock ← Par Terre Defense   Fighting Lock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000196', 'https://www.youtube.com/watch?v=ZpMGBQNmspo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-par-terre-movement — Par Terre — Movement ← Par Terre Defense   Movement
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000197', 'https://www.youtube.com/watch?v=p-MqkxGuSPg', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-pummeling-arm-drag — Pummeling to Arm Drag ← Armdrags & Chops
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000146', 'https://www.youtube.com/watch?v=_h258-ed-no', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-reverse-headlock — Reverse Headlock ← Headlock Defense Part II
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000160', 'https://www.youtube.com/watch?v=gLEabYdy_Tk', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-reverse-lift — Reverse Lift ← Reverse Lift
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000193', 'https://www.youtube.com/watch?v=1gjhBXu4oUM', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-sag-headlock — Sag Headlock ← Headlock Defense Part I   Throw Finish
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000159', 'https://www.youtube.com/watch?v=iAT0HViIXK8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-single-ankle-turn — Single Leg — Ankle Turn Finish ← Sweep Single   Head Inside
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000186', 'https://www.youtube.com/watch?v=1XeFyfGLsY0', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-single-chest-to-back — Single Leg — Chest to Back Finish ← Sweep Single   Head Outside
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000185', 'https://www.youtube.com/watch?v=tOyeuv1xCSs', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-single-outside-finish — Single Leg — Outside Finish ← Sweep Single   Head Outside
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000184', 'https://www.youtube.com/watch?v=tOyeuv1xCSs', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-single-stuff-head — Single Leg Counter — Stuff Head ← Single Leg Counter   Stuff Head
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000188', 'https://www.youtube.com/watch?v=VRussZAawxs', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-snap-down — Snap Down ← Head Snap
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000124', 'https://www.youtube.com/watch?v=-Xi74uWT0vU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-snatch-single — Snatch Single ← Snatch Single
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000118', 'https://www.youtube.com/watch?v=wGwm0qVbu4M', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-sprawl-defense — Sprawl Defense ← Downblock & Sprawl
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000127', 'https://www.youtube.com/watch?v=YKH3oShF3Fc', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-sprawl-to-front-headlock — Sprawl to Front Headlock ← Snap Down to a Front Headlock
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000126', 'https://www.youtube.com/watch?v=0bkIMmQf7TE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-stand-up-turtle — Stand Up from Turtle ← Stand Up
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000199', 'https://www.youtube.com/watch?v=VwytIfWS1Ws', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-takedown-to-par-terre — Takedown to Par Terre ← Transitioning from a Takedown to Par Tarre Offensive
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000198', 'https://www.youtube.com/watch?v=CClAaLPWNp4', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-underhook-duck-under — Underhook — Duck Under ← 2 on 1 Duck Under
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000142', 'https://www.youtube.com/watch?v=cVjTySx1uZ4', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-underhook-entry — Underhook Entry ← Neutral Position - Underhooks Head Position
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000130', 'https://www.youtube.com/watch?v=j3869U-uCCo', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- fs-underhook-hic — Underhook — Hi-C ← High Crotch Inside Step Penetration
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000140', 'https://www.youtube.com/watch?v=witUsu1OzX8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

