-- move_media inserts — review before running
-- generated by match_videos.py

-- Ankle Lace Defense — Catch the Ankle ← Level 3 - Folkstyle Core Curriculum - Counter Offense - Fron
INSERT INTO move_media (move_id, url, media_type) VALUES ('00000000-0000-0000-0002-000000000045', 'https://www.youtube.com/watch?v=SsswVZr11pU', 'youtube') ON CONFLICT DO NOTHING;

-- Front Headlock Reset to Neutral ← Level 3 - Folkstyle Core Curriculum - Counter Offense   Fron
INSERT INTO move_media (move_id, url, media_type) VALUES ('00000000-0000-0000-0002-000000000025', 'https://www.youtube.com/watch?v=slEA1uxj_WE', 'youtube') ON CONFLICT DO NOTHING;

-- Inside Step Penetration — Double Leg ← Level 3 - Folkstyle Core Curriculum - Neutral Position Offen
INSERT INTO move_media (move_id, url, media_type) VALUES ('00000000-0000-0000-0002-000000000009', 'https://www.youtube.com/watch?v=aMXRZM4f6Es', 'youtube') ON CONFLICT DO NOTHING;

-- Snap Down from Inside Tie ← Level 3 - Folkstyle Core Curriculum - Neutral Position - Ins
INSERT INTO move_media (move_id, url, media_type) VALUES ('00000000-0000-0000-0002-000000000011', 'https://www.youtube.com/watch?v=HhIuDiqhgW8', 'youtube') ON CONFLICT DO NOTHING;

-- Sprawl to Front Headlock ← Level 3 - Folkstyle Core Curriculum - Counter Offense   Fron
INSERT INTO move_media (move_id, url, media_type) VALUES ('00000000-0000-0000-0002-000000000051', 'https://www.youtube.com/watch?v=slEA1uxj_WE', 'youtube') ON CONFLICT DO NOTHING;

