-- move_media inserts — review before running
-- generated by match_videos.py
-- content_type on 'drill' rows from 'Drills, Activities and Games'
-- section may need manual correction to 'game' where appropriate

-- ⚠ LOW CONFIDENCE (0.37) — verify this match
-- Ankle Lace Defense — Catch the Ankle ← Level 3 - Folkstyle Core Curriculum - Counter Offense - Front Headlock Clearing 
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000045', 'https://www.youtube.com/watch?v=SsswVZr11pU', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- ⚠ LOW CONFIDENCE (0.36) — verify this match
-- Front Headlock Reset to Neutral ← Level 3 - Folkstyle Core Curriculum - Counter Offense   Front Headlock Knee Tap
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000025', 'https://www.youtube.com/watch?v=slEA1uxj_WE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- ⚠ LOW CONFIDENCE (0.38) — verify this match
-- Inside Step Penetration — Double Leg ← Level 3 - Folkstyle Core Curriculum - Neutral Position Offense - Single Leg Feet
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000009', 'https://www.youtube.com/watch?v=aMXRZM4f6Es', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- ⚠ LOW CONFIDENCE (0.39) — verify this match
-- Snap Down from Inside Tie ← Level 3 - Folkstyle Core Curriculum - Neutral Position - Inside Ties
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000011', 'https://www.youtube.com/watch?v=HhIuDiqhgW8', 'youtube', 'technique') ON CONFLICT DO NOTHING;

-- ⚠ LOW CONFIDENCE (0.37) — verify this match
-- Sprawl to Front Headlock ← Level 3 - Folkstyle Core Curriculum - Counter Offense   Front Headlock Knee Tap
INSERT INTO move_media (move_id, url, media_type, content_type) VALUES ('00000000-0000-0000-0002-000000000051', 'https://www.youtube.com/watch?v=slEA1uxj_WE', 'youtube', 'technique') ON CONFLICT DO NOTHING;

